### ISSUE TITLE
Issues running on x64_mingw

### ISSUE THREAD

**Issue by biximilien** [preston/railroady#82] opened 2015-01-02 03:20 UTC
Hi,

Im receiving the following error message when attempting to run rake diagram:all on x64_mingw platform. GraphViz is installed and on PATH.

Here is the trace:

** Invoke diagram:all (first_time)
** Invoke diagram:setup:create_new_doc_folder_if_needed (first_time)
** Execute diagram:setup:create_new_doc_folder_if_needed
** Invoke diagram:models:complete (first_time)
** Execute diagram:models:complete
railroady -lamM | sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g' | dot -Tsvg > C:/Users/Maxime/Documents/wild-compass/doc/models_complete.svg
'K]' is not recognized as an internal or external command,
operable program or batch file.
rake aborted!
Command failed with status (255): [railroady -lamM | sed -r 's/\x1B\[([0-9]{1...]
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/file_utils.rb:66:in `block in create_shell_runner'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `call'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `sh'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:37:in `sh'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/bundler/gems/railroady-490a01646523/tasks/railroady.rake:65:in `block (3 levels) in <top (required)>'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
c:/Ruby21-x64/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
c:/Ruby21-x64/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
c:/Ruby21-x64/bin/rake:23:in `load'
c:/Ruby21-x64/bin/rake:23:in `<main>'
Tasks: TOP => diagram:all => diagram:models:complete
Generating C:/Users/Maxime/Documents/wild-compass/doc/models_complete.svg

**Comment by preston** [comment] 2015-01-03 17:10
Are you seeing `railroady`, `sed`, and `dot` all on your PATH? All three are necessary.

**Comment by biximilien** [comment] 2015-01-19 12:42
Hmm, they do seem to be on path.

Sorry for the late response.

**Comment by RobertMaaskant** [comment] 2015-12-04 15:38
The problem is in the rake file. Windows sees a pipe symbol in the string passed to the -r option. If you enclose that string in double quotation marks, it does work. Not sure if this would break things in other operating systems.

So change the self.sed in railroady.rake to:

    def self.sed
      regex = 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g'
      case RbConfig::CONFIG['host_os']
      when /linux|cygwin|mingw|mingw32/
        **return "sed -r \"#{regex}\""**
      when /mac|darwin|bsd/
        return "sed -E '#{regex}'"
      else
        fail NotImplementedError
      end
    end

**Comment by preston** [comment] 2015-12-08 01:24
I'm happy to merge this if someone would like to submit a non-breaking patch. I (fortunately) don't have a straightforward way to test Windows-specific changes. :)

**Comment by RobertMaaskant** [comment] 2015-12-08 13:18
The suggested change is working for me on windows. I would be willing to submit a patch, but I don't  know how to test that it is non-breaking (as mentioned in my previous post). Could you point me in the right direction?

**Comment by preston** [comment] 2015-12-08 19:43
If you want to break the "linux" part of that `when` into a separate `when` (so all the Windows stuff is separate), we should be fine. I'm happy to verify on OS X and Ubuntu.

**Comment by preston** [comment] 2016-02-09 15:58
Can I close this out? If there are no outstanding patches I'd like to clear up the issue tracker a bit..

**Comment by RobertMaaskant** [comment] 2016-02-09 16:18
The patch was merged, so yes, this issue can be closed

**Closed** 2016-02-09 16:21 UTC
